pluginName = EHttpEditor Application
pluginProvider = RoiSoleil
productName = EHttpEditor
productBlurb = EHttpEditor\n\
\n\
The HTTP client of IntelliJ, in a small standalone application: write requests in .http files, run them and see the responses.\n\
\n\
https://github.com/RoiSoleil/ehttpeditor
command.newFile = New HTTP File...
command.openFile = Open File...
command.documentation = Documentation
